### ISSUE TITLE
Hydra fails to build the package

### ISSUE THREAD

**Issue by PierreR** [IvanMalison/status-notifier-item#1]
Hydra currently fails to build the package:
https://hydra.nixos.org/job/nixpkgs/trunk/haskellPackages.status-notifier-item.x86_64-linux

I guess this is a simple missing os deps (dbus).

This in turn prevents taffybar-2.0 to be built on `nixos`:
https://hydra.nixos.org/build/73716251

**Comment by colonelpanic8** [comment]
Cool thanks for letting me know.

I'll take a look in a second.

**Comment by colonelpanic8** [comment]
@PierreR The issue seems to be with the dbus dependency. I'm not super familiar with nix, do you think the issue could be with that build?

**Comment by colonelpanic8** [comment]
I'm not really sure why that dependency can be found. I think the best course of action might be to file an issue against nixpackages where people who have more nix knowledge might see it.

**Comment by PierreR** [comment]
Isn't just something like https://github.com/taffybar/taffybar/blob/master/taffybar.cabal#L174 or https://github.com/bartavelle/hruby/blob/master/hruby.cabal#L42 missing for `dbus` ? I know that nixos requires all os dependencies to be specified in the cabal file.

I don't really know how nixpkgs reacts when there is no .cabal file. 

I will do some tests tomorrow and let you know what I have found.

**Comment by colonelpanic8** [comment]
@PierreR I think this is saying that the haskell dependency failed to install.

As far as I can tell, dbus does seem to build

https://hydra.nixos.org/job/nixpkgs/trunk/haskellPackages.dbus.x86_64-linux/all

BUT for some reason, it seems that it hasnt built a new version for a while.

The current version of dbus-1.0.1, which is needed for this package to work. Any idea why that hasn't been built ?

**Comment by PierreR** [comment]
I know it only builds the latest LTS by default (which is dbus-0.10.15 in LTS-11.7). Otherwise you have to make a specific rule to use another version.  I don't believe nixpkgs will read the stack.yaml file at all (but there is a tool called stack2nix).

Anyhow I will take a look at it tomorrow. I probably know how to fix this.

**Comment by colonelpanic8** [comment]
hmm if you look at http://hackage.haskell.org/package/dbus, it claims that 1.0.1 is in NixOS, but if you click on the link, it says the package doesn't exist.

**Comment by PierreR** [comment]
It is available but it isn't the default. The source of truth is this file: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/hackage-packages.nix

I have managed to pass status-notifier-item locally but I now have to deal with the next issue which seems to be `gi-dbusmenu`. I will go to bed and pass the next hurdle tomorrow ;-)

**Comment by colonelpanic8** [comment]
@PierreR gi-dbusmenu is going to need libdbusmenu as a dependency

**Comment by PierreR** [comment]
@IvanMalison The only package that prevents me to build locally in `gtk-sni-tray` via its depency to `gi-dbusmenu`: http://nixpaste.lbr.uno/sK1jyRwo?nix. 
FWIW here is the result of cabal2nix : 
```
λ ~ → cabal2nix cabal://gi-dbusmenu
{ mkDerivation, base, bytestring, Cabal, containers, dbusmenu-glib
, gi-glib, gi-gobject, haskell-gi, haskell-gi-base
, haskell-gi-overloading, stdenv, text, transformers
}:
mkDerivation {
  pname = "gi-dbusmenu";
  version = "0.4.1";
  sha256 = "e4cec1ae6d0acfbb2035e23b45ba7f32477ac2f6d7b900c2d43deb659c3c203a";
  setupHaskellDepends = [ base Cabal haskell-gi ];
  libraryHaskellDepends = [
    base bytestring containers gi-glib gi-gobject haskell-gi
    haskell-gi-base haskell-gi-overloading text transformers
  ];
  libraryPkgconfigDepends = [ dbusmenu-glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi";
  description = "Dbusmenu bindings";
  license = stdenv.lib.licenses.lgpl21;
}
```
I am not quite sure how to solve this given the particularities. Would it be enough to add `libdbusmenu ` to libraryPkgconfigDepends ?

I should probably close this issue because the problem has nothing to do with `status-notifier-item` ;-)

**Comment by PierreR** [comment]
I have created https://github.com/NixOS/nixpkgs/issues/40164
