### ISSUE TITLE
Missing cabal file

### ISSUE THREAD

**Issue by davean** [IvanMalison/status-notifier-item#2]
You seem to be missing the cabal file for this package.

**Comment by colonelpanic8** [comment]
I use hpack to generate it from the package.yaml file. This happens automatically i fyou use stack.

**Comment by davean** [comment]
I for one would appreciate an actual cabal file.

I find cabal new-* satisfies my needs far more than stack.

**Comment by colonelpanic8** [comment]
No need to use stack just use hpack. I don't want to add a generated file to the repo. The cabal file is packaged with releases, but for building from source hpack is required

**Comment by solomon-b** [comment]
I know that you closed this issue years ago, but by not  including a cabal file in the repo you prevent anyone from pinning the library via `cabal.project`. Would you consider changing your policy on this?

**Comment by davean** [comment]
Yah, this remains a major pain point for me using this package still.

**Comment by colonelpanic8** [comment]
This isn't a stack vs cabal thing though. What's wrong with generating the cabal file with hpack?

**Comment by solomon-b** [comment]
`cabal` has the ability to pin a dependency to a git commit/tag in a `cabal.project` file:
```
source-repository-package
  type: git
  location: git@github.com:taffybar/status-notifier-item.git
  tag: v0.3.1.0
  ```
However, I believe this depends on there being a `.cabal` file in the source repository. Because the `.cabal` file is only being generated when a release is built, it is not possible to pin the dependency in a cabal project.

**Comment by colonelpanic8** [comment]
Okay I'll add a cabal file. That said, IIRC, you are using nix no? You should be able to do the exact same thing going through nix..

**Comment by colonelpanic8** [comment]
@solomon-b also you could easily fork the repo, add a cabal file and point to that.

I added the cabal file, but I personally don't like having the cabal file in the repo, when the package.yaml file contains all the information. now I have to make sure to keep both files in sync...

**Comment by solomon-b** [comment]
I use Nix for builds, but `cabal` has a much nicer development experience then `nix build`. 

If you would rather remove the cabal file i can fork the repo. I was hoping to avoid that but I don't want to add an extra burden to your deployment process.

**Comment by colonelpanic8** [comment]
@solomon-b use nix-shell  or nix develop for development (together with cabal new-build)

**Comment by davean** [comment]
Nix uses the cabal file too though. So not having the cabal file also breaks nix (at least on the generation side). What you're saying makes sense if someone is just working with this repository but its a downstream dependency. Break the tooling for this and you break the entire tree. Which is why no one does this as far as I know other than you.

**Comment by colonelpanic8** [comment]
> Nix uses the cabal file too though. So not having the cabal file also breaks nix (at least on the generation side). What you're saying makes sense if someone is just working with this repository but its a downstream dependency. Break the tooling for this and you break the entire tree. Which is why no one does this as far as I know other than you.

I'm pretty sure that cabal2nix takes care of running hpack for you if needed. I know that i use this as nix git depedency and it works just fine.

**Comment by colonelpanic8** [comment]
@davean anyway I added the cabal file, but I stand by my position that its ugly and doesn't really make that much sense.
