### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by nomeata** [IvanMalison/status-notifier-item#6]
http://hackage.haskell.org/package/status-notifier-item says 

> Please see the README on Github at https://github.com/IvanMalison/status-notifier-item#readme

but there is no README. As a clueless user who is trying to upgrade from `System.Taffybar.Systray` (which worked without additional tools) I am a bit lost.

**Comment by colonelpanic8** [comment]
@nomeata Yes, this should have a README.

The relevant README is in https://github.com/taffybar/gtk-sni-tray

this library is basically just support for that, but it also include the status-notifier-watcher binary. basically all you should need to do is run that before starting taffybar.

Alternatively, you can use https://github.com/taffybar/taffybar/blob/62e399d0766ce22109f37257c5ed1968350b5ffb/src/System/Taffybar/Widget/SNITray.hs#L61

There are two problems with this approach

1) You have to be very careful to start any programs that need to register tray icons AFTER taffybar is initialized
2) The watcher dies whenever taffybar dies, so if you restart taffybar, none of the tray icons will be registered anymore

**Comment by nomeata** [comment]
I then used `sniTrayThatStartsWatcherEvenThoughThisIsABadWayToDoIt`, but again, I felt a bit in the dark about why it’s a bad way. Maybe add these two points to the docs of `sniTrayThatStartsWatcherEvenThoughThisIsABadWayToDoIt`?
